### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by VsevolodVikhrov** [muehlemann-popp/django-materialized-view#6]
```
Traceback (most recent call last):
  File "/home/seva/PycharmProjects/devflow-django/src/manage.py", line 22, in <module>
    main()
  File "/home/seva/PycharmProjects/devflow-django/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django_materialized_view/management/commands/migrate_with_views.py", line 46, in handle
    self.view_processor.process_materialized_views()
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django_materialized_view/processor.py", line 35, in process_materialized_views
    self.mark_to_be_applied_new_views()
  File "/home/seva/PycharmProjects/devflow-django/venv/lib/python3.10/site-packages/django_materialized_view/processor.py", line 55, in mark_to_be_applied_new_views
    actual_view_definition_hash = self.__get_hash_from_string(actual_view_definition % args)
TypeError: not enough arguments for format string

```
Percentage sign considered as a placeholder by mistake:
```SQL
LIKE UPPER('%bug%')
```

Suggest to change:
```Python
actual_view_definition_hash = self.__get_hash_from_string(actual_view_definition % args)
```
to
```Python
actual_view_definition_hash = self.__get_hash_from_string(actual_view_definition % args if args else actual_view_definition)
```

**Comment by Sheripov** [comment]
@VsevolodVikhrov Thank you for your help! Fixed as you suggested.
